### ISSUE TITLE
두섭리뷰

### ISSUE THREAD

**Issue by dooseopkim** [dhlee3814/DangSanStudy#1]
1. photo.html 에서
```css
    .content{height:300px; border:solid green; border-width: 0 0 10px 0;}
    .imgWrapper{float:left; margin-left:300px;}
    .image{width:200px; position:relative; margin-top:42px;}
    .tjfaud{float:left; margin-top:42px; margin-left:70px; max-width:350px;}
```
.content에는 height: 300px를 주셨는데 그 하위 .tjfaud는 max-width: 350px를 주셔서  
.content밖으로 글씨들이 넘어갑니다!!  
.content에 overflow속성을 주시거나 .tjfaud의 max-width: 300px로 수정하면 해결 할 수 있지 않을까 합니다!!  
고생하셨습니다.
